defaults: &defaults
  working_directory: ~/historic-rates-line-chart
  docker:
    - image: circleci/node:latest
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  deploy-docs-to-root:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/historic-rates-line-chart
      - run:
          name: Build docs
          command: npm run build-docs
      - run:
          name: Deploy docs
          command: |
            mkdir ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.email "circleci@transferwise.com"
            git config --global user.name "CircleCI"
            npm run deploy-docs-to-dir .
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  deploy-docs-for-branch:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/historic-rates-line-chart
      - run:
          name: Build docs
          command: npm run build-docs
      - run:
          name: Deploy docs
          command: |
            mkdir ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.email "circleci@transferwise.com"
            git config --global user.name "CircleCI"
            npm run deploy-docs-for-branch
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/historic-rates-line-chart
      - run:
          name: Setup npm token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN_PUBLISH" >> ~/.npmrc
      - run:
          name: Build
          command: npm run build
      - run:
          name: Release to GitHub
          command: |
            mkdir ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.email "circleci@transferwise.com"
            git config --global user.name "CircleCI"
            npm run release-to-github
      - run:
          name: Publish on npm
          command: npm publish --access=public

workflows:
  version: 2
  build-and-release:
    jobs:
      - build
      - deploy-docs-to-root:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-docs-for-branch:
          requires:
            - build
          filters:
            branches:
              ignore:
                - master
      - release:
          context: frontend-publish
          requires:
            - deploy-docs-to-root
          filters:
            branches:
              only: master
